### PR TITLE
Automated native_function_invocation fixes

### PR DESCRIPTION
**Pull request by draco2003**
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix ./ --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)

Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

### CODE REVIEW

**Comment by ramsey** [comment]
This breaks certain tests where we inject a mock of the function into the namespace in order to return a known value.

**Comment by draco2003** [comment]
Interesting. Will do a little digging to see if there are any reasonably clean options / work arounds there.

**Comment by ramsey** [comment]
Following up to see if you're still working on this. I did some rebasing in the `4.x` branch, so you'll need to rebase your branch to clear all that up. Sorry about that. Let me know if you have any questions. Thanks!

**Comment by ramsey** [comment]
Checking in again. Let me know if I should leave this open. Thanks!

**Comment by ramsey** [comment]
Closing this PR. Feel free to continue work on it and resubmit if you're able to figure out any workarounds. Thanks!

**Pull request closed without merging**
