### PR TITLE
Change library ircmaxell/random-lib to paragonie/random-lib

### PR DESCRIPTION
**Pull request by karsasmus**
Hello everyone,
UUID V4 depends php7+, the lib ircmaxell/random-lib uses mcrypt modules, which are deprecated in php7. Paragonie's fork doesn't rely on mcrypt* functions.

### CODE REVIEW

**Comment by ramsey** [comment]
Can you check the build and try to run thr tests locally? Also, since the 3.x series supports PHP 5.4-7.2, should this be ported into the master branch, as well? Will paragonie/random-lib work on PHP 5.4?

**Comment by ramsey** [comment]
@mhujer, can you help me understand what is going on in the phpstan failures that are showing up on Travis CI here:

```
5.60s$ composer run phpstan
> @php vendor/phpstan/phpstan-shim/phpstan.phar analyse -c phpstan.neon src --level 2 --no-progress
 -------------------------------------------------------------------------------------------------------- 
  Error                                                                                                   
 -------------------------------------------------------------------------------------------------------- 
  Ignored error pattern #Function Sodium\\randombytes_buf not found# was not matched in reported errors.  
 -------------------------------------------------------------------------------------------------------- 
 [ERROR] Found 1 error                                                          
Script @php vendor/phpstan/phpstan-shim/phpstan.phar analyse -c phpstan.neon src --level 2 --no-progress handling the phpstan event returned with error code 1
```

I do not see these same errors when I run the tests locally on PHP 7.1, and I don't have the sodium extension installed.

I assume this unit test failure is related:

```
1) Ramsey\Uuid\Test\Generator\SodiumRandomGeneratorTest::testGenerateUsesSodiumLibrary
Expectation failed for method name is equal to "delegate" when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```

Again, I can't reproduce this locally. The tests pass.

**Comment by ramsey** [comment]
I rebased the 4.x branch on master. I will handle updating your branch so that there are no conflicts.

**Comment by artemirq** [comment]
@ramsey Any new news about this update?

**Comment by ramsey** [comment]
Merging now.

Thank you for contributing! 🎉

**Pull request merged**
