### PR TITLE
Exclude docs from production

### PR DESCRIPTION
**Pull request by vinkla**
Added `.md` files and the docs directory to be excluded in production.

### CODE REVIEW

**Comment by ramsey** [comment]
Thanks for the PR.

I’ll accept exclusion of the `docs/`, but those markdown files are part of the distribution, IMO. Please see the discussion here: https://github.com/ramsey/uuid/pull/140

**Comment by vinkla** [comment]
> I’ll accept exclusion of the docs/, but those markdown files are part of the distribution, IMO.

I understand your point of view. Though, these files will only be excluded in production. In most cases the `vendor` directory wont be touched in production. The markdown files will just exists without any reason.

**Comment by ramsey** [comment]
The files are excluded from the zip and gz files created for each release here: https://github.com/ramsey/uuid/releases

**Comment by vinkla** [comment]
They will also be excluded when running `composer update --prefer-dist` in the root of your project.

**Comment by ramsey** [comment]
I know. That’s where you want them excluded. I do not want them excluded from the zip or gz distribution files.

**Comment by vinkla** [comment]
> I know. That’s where you want them excluded. I do not want them excluded from the zip or gz distribution files.

Hmm, I don't think there is a way to exclude for Composer only. Shouldn't we target Composer? I'm guessing most people download the package with Composer.

**Comment by ramsey** [comment]
There is not a way to target only Composer. As I’ve already said in previous discussions, to me, these files are part of the distribution in the same way the LICENSE and README.md files are part of the distribution. I do not wish to remove them from the distributed package.

**Comment by vinkla** [comment]
I've pushed an update.

**Comment by ramsey** [comment]
Thanks for contributing! 🎉

**Pull request merged**
