### PR TITLE
Add interface for UUID-related exceptions

### PR DESCRIPTION
**Pull request by shrikeh**
## Description
As the exception thrown during the creating of an instance of a UUID requires intimate knowledge of the codec/builder relationship, I had a delve, and thought the simplest answer would be to give them an interface. This allows catching a `UuidExceptionInterface $e` which will keep the necessary knowledge lighter in the enclosing class.

## How has this been tested?

I ran the existing test suite, after seeing you are catching on specific exceptions. Because the use of the interface to catch is optional, it didn't look like I needed to refactor there, as the tests are after the more specific detail of the exception anyway.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING.md](https://github.com/ramsey/uuid/blob/master/.github/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have run `composer run-script test` locally, and there were no failures or errors. (Well there was one but not related, phan complained about `Method Ramsey\Uuid\Converter\Number\GenericNumberConverter::fromHex() should return string&numeric but returns string.` So it's not my fault ;-)

### CODE REVIEW

**Comment by shrikeh** [comment]
@ramsey Oh mighty god of uuids, what do you think?

**Comment by ramsey** [comment]
Well, I'm not a fan of being acknowledged as a deity. I'm more of a demigod. 😉

I like the feature. I need to decide whether this goes into the next major version or the current 4.x series. Since it introduces an interface and doesn't change one, I *think* it still fits semver to go into the next minor.

**Comment by shrikeh** [comment]
Morning saviour.

While it’s a bit early for more Monty Python quotes, my coffee-withdrawn brain agrees with you that it fits the minor version semver definition, because it’s a backwards compatible feature.

**Comment by ramsey** [comment]
@shrikeh I've released this in v4.2.0. Thanks!

**Pull request merged**
