### PR TITLE
Unit Tests: Add function mock test for systems without libsodium

### PR DESCRIPTION
**Pull request by jmauerhan**
This test allows the UUID library to have coverage of the collaboration between this Generator and libsodium, without the test-runner having to have that library installed. This helps improve coverage and ensure that someone doesn't break that generator and not know it because they can't run the test. 

Because this introduces a new library for function mocking, I wanted to do it as just a small PR for this one test. That library could then be used for a lot of other collaboration tests which are currently being skipped on a lot of systems, if you decide to merge this. 

(Edited for clarity)

### CODE REVIEW

**Comment by jmauerhan** [comment]
Whoops, looks like I need to resolve a different version of the function mocking library.

**Comment by ramsey** [comment]
Whoops!

**Comment by jmauerhan** [comment]
@ramsey since you have seen this, should I go ahead and get it working with the right versions, or is this not something you'd be interested in adding?

**Comment by ramsey** [comment]
Sure thing. I'm interested in adding this. Thanks!

**Comment by jmauerhan** [comment]
Okay cool - didn't want to bother if you already knew you didn't want it :) 👍

**Comment by jmauerhan** [comment]
@ramsey There we go :)

**Comment by ramsey** [comment]
Thanks!

**Pull request merged**
