### PR TITLE
fix: adapt tests to reflect GH-7758

### LINKED ISSUE #425: Broken with 8.1.7
From Fedora CI

See https://koschei.fedoraproject.org/package/php-ramsey-uuid?collection=f36

```
There were 3 failures:
1) Ramsey\Uuid\Test\Rfc4122\UuidV2Test::testGetLocalDomainAndIdentifier with data set #0 (0, Ramsey\Uuid\Type\Integer Object (...), Ramsey\Uuid\Type\Time Object (...), 0, 'person', '12345678', '1b21dd200000000', '-32.723763')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'-32.723763'
+'-33.276237'
/builddir/build/BUILD/uuid-8505afd4fea63b81a85d3b7b53ac3cb8dc347c28/tests/Rfc4122/UuidV2Test.php:110
2) Ramsey\Uuid\Test\Rfc4122\UuidV2Test::testGetLocalDomainAndIdentifier with data set #1 (1, Ramsey\Uuid\Type\Integer Object (...), Ramsey\Uuid\Type\Time Object (...), 1, 'group', '87654321', '1b21dd200000000', '-32.723763')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'-32.723763'
+'-33.276237'
/builddir/build/BUILD/uuid-8505afd4fea63b81a85d3b7b53ac3cb8dc347c28/tests/Rfc4122/UuidV2Test.php:110
3) Ramsey\Uuid\Test\Rfc4122\UuidV2Test::testGetLocalDomainAndIdentifier with data set #2 (2, Ramsey\Uuid\Type\Integer Object (...), Ramsey\Uuid\Type\Time Object (...), 2, 'org', '1', '1b21dd200000000', '-32.723763')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'-32.723763'
+'-33.276237'
/builddir/build/BUILD/uuid-8505afd4fea63b81a85d3b7b53ac3cb8dc347c28/tests/Rfc4122/UuidV2Test.php:110

```

### PR DESCRIPTION
**Pull request by simPod**
Fixes https://github.com/ramsey/uuid/issues/425

### CODE REVIEW

**Comment by simPod** [comment]
cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
This PR targets the wrong branch.

**Comment by simPod** [comment]
Can you specify what branch is the correct one?

**Comment by GrahamCampbell** [comment]
`4.x`

**Comment by GrahamCampbell** [comment]
Wondering if we want to work around the bug in our code, and just keep the test case on the correct behaviour (the PHP 8.1 behaviour is correct).

**Comment by ramsey** [comment]
> Wondering if we want to work around the bug in our code

To clarify, does this affect every version of PHP < 8.1.7? If so, we should probably work around the bug in the code, at least until 8.0 and 8.1 are EOL.

**Comment by ramsey** [comment]
I'll go ahead and merge this, though, so that we can get tests passing on other PRs.

Thank you for contributing! 🎉

**Pull request merged**
