### PR TITLE
Allow brick/math 0.10

### PR DESCRIPTION
**Pull request by alexander-schranz**
## Description

Rebased @remicollet pull request to 4.x: https://github.com/ramsey/uuid/pull/424

## Motivation and context

Add support for brick math 0.10

## How has this been tested?

Running tests locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [-] I have read the **CONTRIBUTING.md** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by simPod — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
Can't be merged with failing tests.

**Comment by alexander-schranz** [comment]
@GrahamCampbell see https://github.com/ramsey/uuid/issues/425

**Comment by GrahamCampbell** [comment]
What I said still stands.

**Comment by GrahamCampbell** [comment]
We need to fix the test assertions, if they are wrong.

**Comment by ramsey** [comment]
Closed in bd2df8d29d7c6801f84179ce3b62915f9fd03636

**Pull request closed without merging**
