### PR TITLE
Fix phpunit deprecation warning

### PR DESCRIPTION
**Pull request by abenerd**
PHPUnit currently spits out warning about the usage of a deprecated function, I refactored the code to use the suggested replacement.
## Description

When running the test suite phpunit spits out the following warning
```bash
assertRegExp() is deprecated and will be removed in PHPUnit 10. Refactor your code to use assertMatchesRegularExpression() instead.
```
I replaced the usage of `assertRegExp` with `assertMatchesRegularExpression`.
## Motivation and context

It removes the usage of currently deprecated code.
## How has this been tested?

The testcase that has been updated still passes.
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by ramsey — APPROVED** [review]

**Comment by ramsey** [comment]
Thanks for contributing!

Unfortunately, this fails on PHP 7.2 :-/

```
Error: Call to undefined method Ramsey\Uuid\Test\Provider\Node\SystemNodeProviderTest::assertMatchesRegularExpression()
```

**Comment by abenerd** [comment]
We could check whether the method exists before calling it and using the old deprecated one as a fallback. But I think for now it would be easier to just wait until support for PHP 7.2 is dropped before changing this. PHPUnit 10 is also going to be a while still, so the tests should work still until we use that.

**Comment by ramsey** [comment]
Sounds good. Thanks!

**Comment by Ocramius** [comment]
This is fixed in #405

**Comment by ramsey** [comment]
Thanks, @Ocramius !

**Pull request closed without merging**
