### PR TITLE
chore(deps): allow brick/math v0.11

### LINKED ISSUE #500: Bump Bump brick/math from ^0.10 to ^0.11
Right now `ramsey/uuid` required `"brick/math": "^0.8.8 || ^0.9 || ^0.10"`.
When I run:
```shell
$ php composer.phar outdated
Info from https://repo.packagist.org: #StandWithUkraine
//
Transitive dependencies not required in composer.json:
brick/math 0.10.2 0.11.0 Arbitrary-precision arithmetic library
```
So it's time to update brick/math to ^0.11.

### PR DESCRIPTION
**Pull request by simPod**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by simPod** [comment]
@ramsey is there any chance to have this 🚢ed soon?

**Comment by ramsey** [comment]
Be patient, please. I've got a lot on my plate, and this PR is only a week old. 🙂

**Comment by simPod** [comment]
Aight, thanks for response!

**Review by ramsey — APPROVED** [review]

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Comment by simPod** [comment]
@ramsey can be have a release? It's blocking brick/math v0.11.0 adoption. Thanks

**Comment by Jimbolino** [comment]
now i know why all my laravel projects are installing 4.x-dev, even with "prefer-stable": true
(and "minimum-stability": "dev")

**Comment by hamrak** [comment]
Hi @ramsey , when is the release of this change planned?

**Comment by ramsey** [comment]
This is released in version 4.7.4. Thank you for your patience.

**Pull request merged**
