### PR TITLE
Support PHP 8.1

### PR DESCRIPTION
**Pull request by GrahamCampbell**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING.md** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Oh, no CI on 3.x branch. Maybe I'll just target 4.x. Not sure what the maintenance policy is here. :)

**Comment by ramsey** [comment]
I haven't tried to get CI working on GitHub Actions since I migrated away from Travis CI. I might try to get it working, since there are so many still using 3.x.

**Comment by GrahamCampbell** [comment]
I guess a better question is, would you like to support PHP 8.1 on the 3.x branch? :)

**Comment by ramsey** [comment]
The answer is "yes." Is this change all it takes, or are there others?

**Comment by GrahamCampbell** [comment]
> Is this change all it takes, or are there others?

Not sure yet. :)

**Comment by GrahamCampbell** [comment]
I've spent a couple of hours trying to get the tests to run. They don't actually run on PHP 8.0 either. I don't think this is worth it. I'm going to focus on the 4.x series instead. This is the only series I personally need to work.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/uuid/runs/3517392859?check_suite_focus=true

**Comment by GrahamCampbell** [comment]
Here's the replacement for the 4.x line: https://github.com/ramsey/uuid/pull/388.

**Comment by ramsey** [comment]
I managed to get the tests running on the 3.x branch on GitHub Actions, with the caveat that there's no way to get them working on 8.0 because some of the dependencies (goaop/framework, codeception/aspect-mock, etc.) do not have versions that will work on 8.0 (even if ignoring platform requirements) because of inconsistencies in the Reflection API.

A very odd thing is all the parse errors on PHP 7.0, though. I can't figure that out.

https://github.com/ramsey/uuid/actions/workflows/continuous-integration.yml?query=branch%3A3.x

**Comment by GrahamCampbell** [comment]
> working on 8.0 because some of the dependencies (goaop/framework, codeception/aspect-mock, etc.) do not have versions that will work on 8.0 (even if ignoring platform requirements) because of inconsistencies in the Reflection API.

Yeh, I ran into the same issue, locally, and gave up at that point.

**Comment by ramsey** [comment]
Tests for 3.x are now passing on PHP 8 (I'm skipping any test that uses AspectMock, but all the important tests are passing). https://github.com/ramsey/uuid/actions/runs/1267144918

**Comment by GrahamCampbell** [comment]
🎉

**Comment by ramsey** [comment]
I ended up committing this to the 3.x branch, btw: https://github.com/ramsey/uuid/commit/9264d240b8de1cca5f7761961781dc3bc9e938e7

**Pull request closed without merging**
