### PR TITLE
Add microtime to the returned DateTime object

### PR DESCRIPTION
**Pull request by ramsey**
Discussed in #90. Currently failing tests and want to be careful not to change tests for the sake of making this work, without considering the implications of the changes to software that depends on this library.

### CODE REVIEW

**Comment by mcneely** [comment]
Perhaps a config setting to toggle microtime on or off? You can keep the original test, toggle it on, then add a test to check it toggled on then.

**Comment by ramsey** [comment]
@mcneely I'm considering setting the minimum required PHP version for the 4.x series to 5.6.15, which would mean all supported PHP versions properly support microtime, and I don't have to worry about supporting it for older PHP versions.

**Comment by azerpas** [comment]
Any plan to add it soon?

**Comment by kalifg** [comment]
I was just looking at this and there was only one failing test:
```
There was 1 failure:

1) Ramsey\Uuid\Test\UuidTest::test32BitMatch64BitForOneHourPeriod
Failed asserting that 1355184000 matches expected 1355184001.0.

/Users/michaeldwyer/src/uuid/tests/src/UuidTest.php:1281
```

This only occurs when `$usec` is >= 500000 and is simply because `round` rounds up when the fractional portion of the timestamp is >= .5.  However `DateTime::getTimestamp()` simply drops the fractional portion.  Changing this

```php
$testTime = round($currentTime + ($usec / 1000000));
```
to this
```php
$testTime = floor($currentTime + ($usec / 1000000));
```

I looked into master, and this isn't a problem because in `Uuid::getDateTime()`, `Uuid::getTimestamp()` returns `1355184000.5`, which `number_format` turns into `1355184001`, matching the logic of `round`.

You said you are reluctant to change the test, but in this case I think you might consider it a correction since the current behavior of returning a rounded-up `DateTime` when presented with microseconds is inconsistent with `DateTime`'s choice to drop them.

**Comment by ramsey** [comment]
This is coming in 4.0.0. I’ve already addressed the rounding issue you mentioned in the `4.x` branch, and I’ll be adding the microtime support soon. Thanks for following up!

**Pull request closed without merging**
