### PR TITLE
Update Psalm and smooth over a few corners

### PR DESCRIPTION
**Pull request by muglug**
## Description
This updates Psalm to the latest version and improves the inferred type safety a little

## Motivation and context
This follows on from https://github.com/ramsey/uuid/pull/282

## How has this been tested?
I ran Psalm and PHPStan

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by muglug** [comment]
Ah, this seems to have broken some test mocking. Will look tomorrow.

**Comment by ramsey** [comment]
Please rebase your branch with `4.x`. I did a little rebasing on that branch, which is why you see all the conflicts listed here. Sorry about that.

**Comment by bdsl** [comment]
@muglug I made some similar changes and got some of the same errors in my branch before I saw that you'd made this PR. Made the mistake of running Psalm locally for each commit, but not running PHPUnit except on Travis when I thought it was done: https://travis-ci.org/bdsl/uuid/jobs/630449180

**Comment by ramsey** [comment]
I’m currently making a lot of changes to the code and will be removing some classes and adding others, so you might want to wait until that’s done to try to clean up all the Psalm errors. 🙂

**Comment by muglug** [comment]
ok!

**Pull request closed without merging**
